### ISSUE TITLE
Request: Rename repo to "architecture-decision-records"

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/architecture-decision-records#6]
`ADR` isn't immediately obvious to someone what this repo is based on the name.

It would be great to rename this to the non-abbreviated name to make it more understandable what this repo is directly from the GitHub repo list.

**Comment by gregsheremeta** [comment]
I would agree.

@LaVLaS is that fairly easy to do?

**Comment by strangiato** [comment]
It should be the first option under settings on the repo:

![image](https://user-images.githubusercontent.com/1628206/227317440-d603853f-6b1f-48e2-924a-0209d7da70ab.png)

It will change the slug of the URL but the old URL should still function so anyone that has the repo cloned or linked to the repo won't have to update anything.

**Comment by strangiato** [comment]
I love the idea of the repo BTW!  Can't wait to see more stuff coming through here.

**Comment by gregsheremeta** [comment]
well, it's renamed now (I assume by Landon :joy: ) so we're all good. thanks!
